# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory
WORKDIR /pmldlapp

# Set environment variables
ENV PROJECTPATH=/pmldlapp

RUN pip install fastapi uvicorn scikit-learn pandas
# Copy the current directory contents into the container at /app

COPY code/deployment/api /pmldlapp/code/deployment/api   
COPY code/models /pmldlapp/code/models 
COPY models /pmldlapp/models

WORKDIR /pmldlapp/code/deployment/api


# Run the FastAPI server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
